### PR TITLE
Remove all ball joints on crane

### PR DESCRIPTION
**Pull request by Adimote**
The crane robot currently has some weird behavior, it acts completely solid until the crane picks up a cube. After picking up a cube the cube swings around. The problem here is when you let go of the cube, the hook starts behaving weirdly:  when you move around it snaps to an angle, no matter which direction you move it.

Also, this solves an issue with the radar rotation being inconsistent due to the hook swinging around.

### CODE REVIEW

**Comment by jefftheprogrammer** [comment]
The cube and the hook no-longer swings around.

**Review by jefftheprogrammer — APPROVED** [review]
Problem is fixed

**Comment by RealOrangeOne** [comment]
Instead of this, is it possible to move the receiver instead so it's outside the ball joint (and thus not affected by it). This way there are fewer simulator changes, and fewer rigid bodies which hopefully reduces the chances of "yeeting".

**Comment by jefftheprogrammer** [comment]
@Adimote hello. We have a new idea. Can you move the transmitter to the ball joint (where the hook joins the rigid cable)?

**Comment by Adimote** [comment]
closed in favour of #75

**Comment by WillB97** [comment]
The issues with yeeting tokens is a bug where the balljoints are are exceeding their limits. the motors all have a maximum force set so it would be more stable without balljoints.

**Comment by PeterJCLaw** [comment]
Suggest we close this as it's no longer relevant?

**Pull request closed without merging**
