### PR TITLE
Add initial token design

### LINKED ISSUE #7: Create tokens
These will likely be cube or cuboid shape with someway the identify which team they belong to.
Additional tweaking will also be needed to the mass and physics damping to reduce the issues with tokens being ejected.
To allow the tokens to be picked up by the crane, [connectors](https://cyberbotics.com/doc/reference/connector) need to be added to all the faces.

### PR DESCRIPTION
**Pull request by WillB97**
The emitter is currently commented out while we figure out how the radio's will work.
The whole token will be in the team's colour

Arena_35

Will fix #7

### CODE REVIEW

**Comment by WillB97** [comment]
We can tune the Connector parameters once the crane robot has been created.

**Review by Dasepho — APPROVED** [review]
Great work :)
Dimensions are tbd I think, so we will come back and finalise them when they're decided (e.g. cuboids to match shipping containers)

**Review by sedders123 — APPROVED** [review]

**Review by RealOrangeOne — APPROVED** [review]
image


Given the size of these tokens, should we make the walls taller? I can definitely see collisions "yeeting" these tokens out of the arena.

**Comment by sedders123** [comment]
We were going to add an invisible wall all the way around the arena to prevent yeetage

**Comment by WillB97** [comment]
That merged into the wrong branch and broke #30, 8ba3792df03e7b05863962ff00d14f2128389b5b is this merge in the correct place.

**Pull request merged**
